# Generated by Django 3.1.7 on 2021-04-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='original_bag',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_pid',
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_volume',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
