# Generated by Django 3.1.7 on 2021-04-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210430_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_volume',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
